name: Check Pull Request Quality

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Use Dependencies Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Set test .env file
        run: cp .env.example .env
      - name: Run tests
        run: npm run test